### ISSUE TITLE
Recording problem

### ISSUE THREAD

**Issue by c7v** [Ferk/udev-media-automount#16]
Hi all. Thanks to the authors for their work.

flash software works fine, but when I inserted an external hard drive and it mounted. I tried to create a folder on the disk using the command: mkdir. however I received an error. 

```console
web@server:/media/ExternalDisk.ntfs$ mkdir knowledge_base
mkdir: cannot create directory ‘knowledge_base’: Read-only file system
```

Maybe something needs to be added to the config /etc/media-automount.d/ntfs?

**Comment by c7v** [comment]
Found the problem, the problem was that the software was running as root.

```console
web@server:~$ ls -al /media/ExternalDisk.ntfs/
total 8
drwxrwxrwx 1 root root 4096 сен 13 11:09 .
drwxr-xr-x 3 root root 4096 сен 13 11:10 ..
```

**Comment by Ferk** [comment]
The issue is not that the owner of the directory is root. Because as you can see, the permissions are `drwxrwxrwx`, meaning that everyone would have been allowed to write on it.

The reason you can't write is because it was mounted 'Read-only'. In fact, I expect even as root you would not be able to write on it, it would have to be remounted.

Most likely, the cause of the issue is the NTFS filsystem being locked, probably because of a previous Windows session not cleanly closing the filesystem, like in this example: https://superuser.com/questions/1743578/not-possible-to-mount-windows-11-ntfs-partition-for-read-write-even-with-fast
